### ISSUE TITLE
Sequences

### ISSUE THREAD

**Issue by agame3415** [Dennetix/KrunkerWSBot#1]
Where can I find the sequences for the shifting operations at https://github.com/Dennetix/KrunkerWSBot/blob/52d4aa93b920d2d0eac542f77039811019b774f0/src/client/Client.ts#L253

**Comment by Dennetix** [comment]
Don't know if you're still looking for this but the sequences change per version. I just looked at the last two bytes that the official client includes in every message and figured out the sequence from that. I also built KrunkerWSInspector to automate this, it shows the sequences in the top right.
